---
title: "03_analytic_data"
author: "Puvvula"
date: "2023-07-18"
output: pdf_document
---

```{r}
library(pacman)
pacman::p_load(tidyverse, janitor)

dat_loc <- "~/Documents/ope_ssis/data/"
res<- "~/Documents/ope_ssis/result/"
```

#join exposure, outcome and covars
```{r}
exp_dat<- read_csv(paste0(dat_loc, "exp_dat.csv"))
out_cov<- read_csv(paste0(dat_loc, "out_cov.csv"))

df<- full_join(exp_dat, out_cov, by="participant_id") |>
  filter(if_any(34:60, ~ !is.na(.))) # drop observations if any outcome or covariates are missing

write_csv(df, paste0(dat_loc, "analytic_set.csv"))
```

#summary of analytic dataset
```{r}
summary_stats<- df |>
  select(-c(1)) |>
  select(where(is.numeric)) |>
  pivot_longer(everything(), names_to = "metric", values_to = "value") |>
  group_by(metric) |>
  summarize(NR_interference = paste(sum(value == 9999, na.rm = TRUE), "(", 
                                    round((sum(value == 9999, na.rm = TRUE) / length(value)) * 100, 2), "%)"),
            Below_LOD = paste(sum(value == 8888, na.rm = TRUE), "(", 
                                    round((sum(value == 8888, na.rm = TRUE) / length(value)) * 100, 2), "%)"),
            Unmeasured = paste(sum(value == 7777, na.rm = TRUE), "(", 
                                    round((sum(value == 7777, na.rm = TRUE) / length(value)) * 100, 2), "%)"),
            Reportable_values = paste(sum(value < 500, na.rm = TRUE), "(", 
                                    round((sum(value <500, na.rm = TRUE) / length(value)) * 100, 2), "%)"),
            median_iqr = paste(
              round(quantile(value[value < 500], 0.5, na.rm = TRUE), 2), "(",
              round(quantile(value[value < 500], 0.25, na.rm = TRUE), 2), "-", 
              round(quantile(value[value < 500], 0.75, na.rm = TRUE), 2), ")"
              ))

write_csv(summary_stats, paste0(res, "summary_analytic_dat.csv"))
```

#for revision
```{r}
exp_dat<- read_csv(paste0(dat_loc, "exp_dat.csv")) |>
  pivot_longer(cols = -participant_id, names_to = "metric", values_to = "value") |>
  extract(metric, into = c("analyte", "visit"), regex = "^([^_]+)_(.*)$") |>
  mutate(value = na_if(value, 9999),
         value = na_if(value, 7777)) |>
  drop_na(value)

#full summary
summary_table <- exp_dat |>
    mutate(period = if_else(str_starts(visit, "postnatal"),
                            "child",
                            "gestation")) |>
    distinct(participant_id, visit, period) |>
    group_by(participant_id, period) |>
    summarise(n_visits = n(), .groups = "drop") |>
    pivot_wider(names_from = period, values_from = n_visits, values_fill = 0) |>
    mutate(lifetime = gestation + child) |>
    count(gestation, child, lifetime, name = "n_participants")

#for publication summary
summary_table <- exp_dat |>
  mutate(period = if_else(str_starts(visit, "postnatal"),
                          "child",
                          "gestation")) |>
  distinct(participant_id, visit, period) |>
  group_by(participant_id, period) |>
  summarise(n_visits = n(), .groups = "drop") |>
  pivot_wider(names_from = period, values_from = n_visits, values_fill = 0) |>
  mutate(
    lifetime = gestation + child,
    gestation_group = if_else(gestation < 2, "<2", "≥2"),
    child_group = if_else(child < 4, "<4", "≥4"),
    lifetime_group = if_else(lifetime < 4, "<4", "≥4")
  ) |>
  count(gestation_group, child_group, lifetime_group, name = "n_participants")
```





