---
title: "04_corr_descri_figs"
author: "Puvvula"
date: "2023-07-18"
output: pdf_document
---

```{r}
library(pacman)
pacman::p_load(tidyverse, janitor, psych, reshape2, qgcomp, BlandAltmanLeh)

dat <- "~/Documents/ope_ssis/data/"
res<- "~/Documents/ope_ssis/result/"
```

#read analytic set
```{r}
df<- read_csv(paste0(dat, "analytic_set.csv")) 

df_sorted <- df %>%
  select(1, sort(names(.)[2:13]), everything())

write_csv(df_sorted, paste0(dat, "analytic_set.csv")) # replacing the original with variable seq sorted format
```

#correlation matrix
```{r}
corr <- df_sorted |>
  select(c(2:13)) |>
  cor(method = "pearson", use="complete.obs") |> 
  melt()

ggplot(corr, aes(x = Var1, y = Var2, fill = value)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", 
                       midpoint = 0, breaks = seq(-1, 1, 0.2)) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        strip.text = element_text(colour = "black", size = 8),
        strip.text.x = element_text(colour = "black", size = 6.5),
        strip.text.y = element_text(colour = "black", size = 6.5)) +
  labs(title = "", x = "", y = "") +
  geom_text(aes(label = round(value, 2)), color = "black", size = 3)+
  guides(fill=FALSE)

ggsave(paste0(res, "corr_plt.tiff"), 
       width = 5,height = 5,
       dpi=300)
```

#interclass correlation function
```{r}
icc_function <- function(data, chemical_prefixes, num_time_points) {
  icc_results <- list()
  
  for (prefix in chemical_prefixes) {
    # Create a regular expression pattern for variable matching
    pattern <- paste0("^", prefix, "_\\w+$")
    
    # Subset the data to include only the variables matching the pattern
    subset_data <- data[, grep(pattern, names(data))]
    
    # Calculate the interclass correlation using ICC()
    icc_result <- ICC(subset_data, missing=TRUE, alpha=0.5, lmer=TRUE,check.keys=TRUE)
    
    icc_results[[prefix]] <- icc_result
  }
  
  return(icc_results)
}
```

#get ICC results
```{r}
chemicals <- c("bcep", "bdcipp", "dnbp", "dphp")
result <- icc_function(data = df_sorted, 
                       chemical_prefixes = chemicals, 
                       num_time_points = 3)

print(result)

#bcep: 0.15 (0.12-0.18); bdcipp: 0.23 (0.20-0.26); dnbp: 0.00026 (-0.00017-0.00073); dphp: 0.11 (0.086-0.14)
```


