---
title: "05_mi_multi_inf"
author: "Puvvula"
date: "2023-07-18"
output: pdf_document
---

```{r}
library(pacman)
pacman::p_load(tidyverse, janitor, qgcomp, norm, mice, geepack, parallel)

dat_loc <- "~/Documents/ope_ssis/data/"
res<- "~/Documents/ope_ssis/result/"
```

#SKIP UNTIL LINE 93 - which loads the imputed datasets from an R object

```{r}
dat<- read_csv(paste0(dat_loc, "analytic_set.csv")) |>
  select(-c(dnbp_postnatal_1_yr, dnbp_postnatal_2_yr)) #discussed with aimin and removing these observations as they have >85% obs below LOD
```


#multiple imputation of exposures below LOD
```{r}
#convert into long format by each visit
dat_long <- dat |>
  pivot_longer(cols = 2:35, names_to = "variable", values_to = "value") |>
  extract(variable, into = c("chemical", "visit"), regex = "([^_]+)_(.*)", remove = FALSE) |>
  pivot_wider(names_from = chemical, values_from = value) |>
  mutate(visit = case_when(visit == "prenatal_16W" ~ "baseline", TRUE ~ visit))

#========================================================#
#split into 4 sets by each chemical for imputation
#Split the dataframe into 4 sets

# Create a list to store the dataframes
dataframes <- list()

# Loop through each prefix and create a dataframe for each group
for (prefix in c("bcep", "bdcipp", "dnbp", "dphp")) {
  # Filter the dataframe based on the prefix
  new_df <- dat_long %>%
    filter(str_starts(variable, prefix)) %>%
    select(-variable)  # Remove the variable column if needed
  
  # Drop variables that only contain NA values for all observations
  new_df <- new_df[, apply(new_df, 2, function(x) any(!is.na(x)))]
  
  # Store the dataframe in the list
  dataframes[[prefix]] <- new_df
}

#========================================================#
# Assign the separate dataframes to individual objects
list2env(setNames(dataframes, paste0("dat_", sapply(dataframes, function(df) tail(colnames(df), 1)))), .GlobalEnv)
```

#remove not reported values due to interference
```{r}
dat_bcep<- drop_NR_interference(dat_bcep, "bcep")
dat_dnbp<- drop_NR_interference(dat_dnbp, "dnbp") 
dat_dphp<- drop_NR_interference(dat_dphp, "dphp")
dat_bdcipp<- drop_NR_interference(dat_bdcipp, "bdcipp")
```
#=======================================================#
#n after dropping NR interference
bcep = 219
dnbp = 183 (7 time points only)
dphp = 228
bdcipp = 220
#=======================================================#

#just for exposure summaries
```{r}
# List of datasets
datasets <- list(dat_bcep, dat_dnbp, dat_dphp, dat_bdcipp)
dataset_names <- c("dat_bcep", "dat_dnbp", "dat_dphp", "dat_bdcipp")

# Function to process each dataset
process_dataset <- function(dataset, dataset_name) {
  # Select the last two variables and participant_id
  selected_vars <- dataset %>%
    select(participant_id, last_col() - 1, last_col())  # Select participant_id and the last two variables
  
  # Rename the last variable as "value"
  selected_vars <- selected_vars %>% rename(value = names(.)[3])
  
  # Add a new variable for dataset name
  selected_vars <- selected_vars %>% mutate(dataset_name = dataset_name)
  
  return(selected_vars)
}

# Apply the function to each dataset
processed_datasets <- map2_df(datasets, dataset_names, process_dataset)

#correcting visit labels:
processed_datasets_x <- processed_datasets |>
  mutate(visit = recode(visit, "postnatal_8_yr" = "postnatal_12_yr"))|>
  mutate(visit = recode(visit, "postnatal_5_yr" = "postnatal_8_yr")) |>
  mutate(visit = recode(visit, "postnatal_4_yr" = "postnatal_5_yr"))
#=============================================================================#
#summary tbl
summary_stats <- processed_datasets_x %>%
  group_by(dataset_name, visit) %>%
  summarise(
    summary = paste(round(median(value, na.rm = TRUE), 2), 
                    " (", round(quantile(value, 0.25, na.rm = TRUE), 2), ", ", 
                    round(quantile(value, 0.75, na.rm = TRUE), 2),")")
  ) |>
  pivot_wider(names_from = dataset_name, values_from = summary)

write_csv(summary_stats, paste0(res, "opfr_summary_pre_imp.csv"))
#=============================================================================#
#correlation matrix
cor_dat<- processed_datasets_x |>
  filter(visit != "postnatal_12_yr") |>
  mutate(dataset_name = sub("dat_", "", dataset_name)) |>
  mutate(visit = recode(visit, "baseline" = "16w")) |>
  mutate(dataset_name = toupper(dataset_name)) |>
  mutate(visit = str_to_title(visit))|>
  mutate(var = paste(dataset_name, visit, sep = "_")) |>
  select(-c(dataset_name, visit)) |>
  pivot_wider(names_from = var, values_from = value) |>
  select(-c(participant_id))|>
  rename_with(~ str_replace_all(., "_(16w)$", "_Prenatal_\\1"), -1) |>
  rename_at(vars(contains("Postnatal_")), ~ str_replace(., "Postnatal_", "Child_"))


#mapping
visit_mapping <- c(
  "BCEP_Prenatal_16w", "BCEP_Prenatal_26w", "BCEP_Delivery", "BCEP_Child_1_yr", "BCEP_Child_2_yr", 
  "BCEP_Child_3_yr", "BCEP_Child_5_yr", "BCEP_Child_8_yr",
  "BDCIPP_Prenatal_16w", "BDCIPP_Prenatal_26w", "BDCIPP_Delivery", "BDCIPP_Child_1_yr", "BDCIPP_Child_2_yr", 
  "BDCIPP_Child_3_yr", "BDCIPP_Child_5_yr", "BDCIPP_Child_8_yr",
  "DNBP_Prenatal_16w", "DNBP_Prenatal_26w", "DNBP_Delivery", "DNBP_Child_1_yr", "DNBP_Child_2_yr", 
  "DNBP_Child_3_yr",  "DNBP_Child_5_yr", "DNBP_Child_8_yr",
  "DPHP_Prenatal_16w", "DPHP_Prenatal_26w", "DPHP_Delivery", "DPHP_Child_1_yr", "DPHP_Child_2_yr", 
  "DPHP_Child_3_yr", "DPHP_Child_5_yr", "DPHP_Child_8_yr"
)


# Calculate Spearman correlation matrix
cor_matrix <- cor(cor_dat, method = "spearman", use = "pairwise.complete.obs")
cor_matrix_rnd <- round(cor_matrix, digits = 2)

# Melt the correlation matrix for ggplot
melted_cor_matrix <- melt(cor_matrix_rnd) |>
  mutate_at(vars(Var1, Var2), ~factor(., levels = rev(visit_mapping)))

ggplot(melted_cor_matrix, aes(x = Var2, y = Var1, fill = value, label=value)) + #, label = value
  geom_tile(color = "white") +
  geom_text(color = "black", size = 3, vjust = 1) +
  scale_fill_gradient2(low = "red", high = "blue", mid = "white",
                       midpoint = 0,
                       limit = c(-1, 1), space = "Lab",
                       name = "Spearman correlation coefficient") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 11, hjust = 1),
        axis.text.y = element_text(angle = 0, vjust = 0.5, size = 11, hjust = 1),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.major = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "bottom", legend.box = "horizontal") +
  coord_fixed()+
  geom_hline(yintercept = c(0, 8.5, 14.5, 22.5, 31.5), color = "black", size = 0.8) +
  geom_vline(xintercept = c(0, 8.5, 14.5, 22.5, 31.5), color = "black", size = 0.8)

ggsave(paste0(res, "opfr_correlation_heatmap.tiff"),
       width=10, height= 10, dpi=300)
```


# generate imputed datasets
```{r}
imputed_datasets <- generate_imputed_datasets(dat_bcep, dat_dnbp, dat_dphp, dat_bdcipp)
# Access the imputed datasets
imp_dat_bcep <- imputed_datasets[[1]]
imp_dat_dnbp <- imputed_datasets[[2]]
imp_dat_dphp <- imputed_datasets[[3]]
imp_dat_bdcipp <- imputed_datasets[[4]]

# Clear the global environment for non-imputed datasets
for (obj in ls()) {
  if (!grepl("^imp_dat_", obj)) {
    rm(list = obj, envir = .GlobalEnv)
  }
}

save(imp_dat_bcep, imp_dat_bdcipp, imp_dat_dnbp, imp_dat_dphp, 
     file = paste0("~/Documents/ope_ssis/data/opfr_imputed_objects.rda"))
```

#load imputed datasets
```{r}
load(paste0(dat_loc, "opfr_imputed_objects.rda"))
```

#for testing
```{r}
runGeeglmParallel(datasets = c("imp_dat_dphp", "imp_dat_bcep", "imp_dat_bdcipp", "imp_dat_dnbp"), 
                  covariates = c("gender", "child_race", "mat_age", "mari_st_p4", "mom_edu_p4_cat",
                                 "mid_income_p4", "cotinine" , "bdi_p4", "lead", "rfr_gs_t"),
                  outcomes = c("ss_std_score_c", "com_raw_c", "coop_raw_c", "assert_raw_c","res_raw_c",
                              "emp_raw_c", "eng_raw_c", "self_raw_c", "pb_std_score_c", "ext_raw_c",
                              "bul_raw_c", "hyp_raw_c", "int_raw_c", "ss_std_score_p", "com_raw_p",
                              "coop_raw_p", "assert_raw_p", "res_raw_p", "emp_raw_p", "eng_raw_p",
                              "self_raw_p", "pb_std_score_p", "ext_raw_p", "bul_raw_p", "hyp_raw_p",
                              "int_raw_p", "as_raw_p"),
                  outputFolder = "~/Documents/ope_ssis/result/gee_mi_res_feb")
```

```{r}
load("~/Documents/ope_ssis/result/gee_mi_res_feb/imp_dat_dphp_as_raw_p_dphp.rda")
x<-as_tibble(tidy(pool(fit), conf.int = TRUE))
```


#get estimates as csv
```{r}
extractGEEParallel(input_folder="~/Documents/ope_ssis/result/gee_mi_res_feb", 
                   output_folder= "~/Documents/ope_ssis/result/gee_mi_res_feb")
```

