---
title: "06_visualizing_results"
author: "Puvvula"
date: "2023-08-07"
output: pdf_document
---

```{r}
library(pacman)
pacman::p_load(tidyverse, janitor, ggh4x)

res<- "~/Documents/ope_ssis/result/gee_mi_res_feb/"
```

#data prep for visualization
```{r}
df_res<- read_csv(paste0(res, "output.csv")) |>
  mutate(exposure = toupper(exposure),
         term = case_when(
           term == "log(get(exposure))" ~ as.character(exposure),
           TRUE ~ paste0(as.character(exposure), "-", str_extract(term, "(?<=:)[^:]+$")))) |>
  select(c(1,2,5:7,17)) |>
  mutate(outcome_set = ifelse(grepl("p$", outcome), "Parent", "Child"),
         outcome_label = factor(str_remove(outcome, "_[pc]$")),
         outcome_label = fct_recode(outcome_label,
                                    Social_skills_scale = "ss_std_score",
                                    Communication = "com_raw",
                                    Cooperation = "coop_raw",
                                    Assertion = "assert_raw",
                                    Responsibility = "res_raw",
                                    Empathy = "emp_raw",
                                    Engagement = "eng_raw",
                                    Self_control = "self_raw",
                                    Problem_behaviors_scale = "pb_std_score",
                                    Externalizing = "ext_raw",
                                    Bullying = "bul_raw",
                                    Hyperactivity_inattention = "hyp_raw",
                                    Internalizing = "int_raw",
                                    Autism_spectrum = "as_raw"),
         outcome_category = case_when(outcome_label %in% 
                                        c("Communication", "Cooperation", "Assertion", 
                                          "Responsibility", "Empathy", "Engagement", 
                                          "Self_control", "Social_skills_scale") ~ "Social Skills",
                                      TRUE ~ "Problem Behavior"),
         across(where(is.numeric), ~ round(., 3)),
         significance = ifelse(p.value < 0.05, "signf", "non_sign")) |>
  clean_names() |>
  select(1,2,4:10)
```

```{r}
sequence <- 1:918
repetition_indices <- c(rep(sequence[1:54], each = 9), rep(sequence[55:81], each = 7), rep(sequence[82:108], each = 9))

# Use group_by and summarize to calculate row sums for each group
result <- df_res |>
  group_by(repetition = repetition_indices) |>
  mutate(
    estimate = ifelse(row_number() != 1, estimate + first(estimate), estimate),
    conf_low = ifelse(row_number() != 1, conf_low + first(conf_low), conf_low),
    conf_high = ifelse(row_number() != 1, conf_high + first(conf_high), conf_high)
  ) |>
  ungroup() |>
  mutate(term = fct_recode(term,
                           "BCEP_Prenatal_16W" = "BCEP",
                           "BCEP_Prenatal_26W" = "BCEP-visitprenatal_26W",
                           "BCEP_Delivery" = "BCEP-visitdelivery",
                           "BCEP_Postnatal_1_yr" = "BCEP-visitpostnatal_1_yr",
                           "BCEP_Postnatal_2_yr" = "BCEP-visitpostnatal_2_yr",
                           "BCEP_Postnatal_3_yr" = "BCEP-visitpostnatal_3_yr",
                           "BCEP_Postnatal_4_yr" = "BCEP-visitpostnatal_4_yr",
                           "BCEP_Postnatal_5_yr" = "BCEP-visitpostnatal_5_yr",
                           "BCEP_Postnatal_8_yr" = "BCEP-visitpostnatal_8_yr",
                           "BDCIPP_Prenatal_16W" = "BDCIPP",
                           "BDCIPP_Prenatal_26W" = "BDCIPP-visitprenatal_26W",
                           "BDCIPP_Delivery" = "BDCIPP-visitdelivery",
                           "BDCIPP_Postnatal_1_yr" = "BDCIPP-visitpostnatal_1_yr",
                           "BDCIPP_Postnatal_2_yr" = "BDCIPP-visitpostnatal_2_yr",
                           "BDCIPP_Postnatal_3_yr" = "BDCIPP-visitpostnatal_3_yr",
                           "BDCIPP_Postnatal_4_yr" = "BDCIPP-visitpostnatal_4_yr",
                           "BDCIPP_Postnatal_5_yr" = "BDCIPP-visitpostnatal_5_yr",
                           "BDCIPP_Postnatal_8_yr" = "BDCIPP-visitpostnatal_8_yr",
                           "DPHP_Prenatal_16W" = "DPHP",
                           "DPHP_Prenatal_26W" = "DPHP-visitprenatal_26W",
                           "DPHP_Delivery" = "DPHP-visitdelivery",
                           "DPHP_Postnatal_1_yr" = "DPHP-visitpostnatal_1_yr",
                           "DPHP_Postnatal_2_yr" = "DPHP-visitpostnatal_2_yr",
                           "DPHP_Postnatal_3_yr" = "DPHP-visitpostnatal_3_yr",
                           "DPHP_Postnatal_4_yr" = "DPHP-visitpostnatal_4_yr",
                           "DPHP_Postnatal_5_yr" = "DPHP-visitpostnatal_5_yr",
                           "DPHP_Postnatal_8_yr" = "DPHP-visitpostnatal_8_yr",
                           "DNBP_Prenatal_16W" = "DNBP",
                           "DNBP_Prenatal_26W" = "DNBP-visitprenatal_26W",
                           "DNBP_Delivery" = "DNBP-visitdelivery",
                           "DNBP_Postnatal_3_yr" = "DNBP-visitpostnatal_3_yr",
                           "DNBP_Postnatal_4_yr" = "DNBP-visitpostnatal_4_yr",
                           "DNBP_Postnatal_5_yr" = "DNBP-visitpostnatal_5_yr",
                           "DNBP_Postnatal_8_yr" = "DNBP-visitpostnatal_8_yr"
                            ))  |>
  filter(!str_detect(term, "Postnatal_8_yr$")) |>
  mutate(term = str_replace(term, "(.*)Postnatal_5_yr$", "\\1Child_8_yr"))|>
  mutate(term = str_replace(term, "(.*)Postnatal_4_yr$", "\\1Child_5_yr")) |>
  mutate(term = str_replace(term, "(.*)Postnatal_4_yr$", "\\1Child_5_yr")) |>
  mutate(term = str_replace(term, "Postnatal", "Child"))|>
  mutate(
    chemical = str_extract(term, "^[^_]+"),
    visit = str_remove(term, "^[^_]+_")
  ) |>
  mutate(outcome_set = recode(outcome_set, "Parent" = "Caregiver", "Child" = "Adolescent"))
```

#reorder y axis levels
```{r}
result$visit <- factor(result$visit, levels = c(
  "Prenatal_16W",
  "Prenatal_26W",
  "Delivery",
  "Child_1_yr",
  "Child_2_yr",
  "Child_3_yr",
  "Child_5_yr",
  "Child_8_yr"
))
```

# plot
```{r}
cbbPalette <- c("#D55E00", "#0072B2")

ggplot(result, aes(y = fct_rev(visit), x = estimate, xmin = conf_low, xmax = conf_high)) + 
  geom_pointrange(aes(color = ifelse(conf_low <= 0 & conf_high >= 0, "Contains 0", "Doesn't contain 0")), 
                  position = position_dodge(width = 0.5), size = 0.6)+
  geom_vline(aes(xintercept = 0), linetype="dashed") + 
  facet_nested(outcome_set+chemical ~ outcome_category+outcome_label, scales="free")+
  scale_colour_manual(values=cbbPalette) +
  labs(y=NULL,
       x=expression(paste(beta[GEE-glm]," [95% CI]")),
       title = "",
       caption = "")+
  theme_bw()+
  theme(axis.line = element_line(colour = "black"),
        plot.title=element_text(size = 10, hjust = 0),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        text=element_text(size=10),
        axis.text = element_text(size = 10),
        axis.text.x=element_text(size=10, angle = 45, hjust=0.8),
        axis.ticks.x=element_blank(),
        strip.text.x=element_text(size=7,angle=0),
        strip.text.y = element_text(size=10),
        strip.placement = "outside",
        strip.background = element_rect(fill="transparent", colour = NULL),
        panel.spacing.x = unit(0.1, "lines"),
        panel.spacing.y = unit(0.1, "lines"))+
  guides(color="none")
```

#export
```{r}
ggsave(paste0(res, "gee_glm.tiff"), 
       width = 18,height = 10,
       dpi=300)
```


